config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope :slack do
    post 'events', to: 'slack#events'
    get 'authorize', to: 'slack#authorize'
  end

  resource :organization, only: %i[show edit update]

  # Limit access to dev only.
  mount GoodJob::Engine => 'q' if Rails.env.development?

  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authorization.rb
# frozen_string_literal: true

class Authorization < ApplicationRecord
  belongs_to :organization
  validates :uid, uniqueness: { scope: :platform }
  scope :slack, -> { where(platform: 'Slack') }
end

app/models/conferral.rb
# frozen_string_literal: true

class Conferral < ApplicationRecord
  belongs_to :giver, class_name: 'Persona', inverse_of: :given_conferrals
  belongs_to :receiver, class_name: 'Persona', inverse_of: :received_conferrals
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  enum status: { pending: 0, processing: 1, completed: 2, failed: 3 }
  scope :slack, -> { where(platform: 'Slack') }
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  has_many :authorizations, dependent: :destroy
  has_many :personas, dependent: :destroy
  validates :name, presence: true

  after_initialize :set_defaults, if: :new_record?

  def set_defaults
    self.emoji = 'taco'
    self.daily_budget = 5
  end
end

app/models/persona.rb
# frozen_string_literal: true

class Persona < ApplicationRecord
  belongs_to :organization
  has_many :given_conferrals, class_name: 'Conferral', foreign_key: 'giver_id', dependent: :destroy,
                              inverse_of: :giver
  has_many :received_conferrals, class_name: 'Conferral', foreign_key: 'receiver_id', dependent: :destroy,
                                 inverse_of: :receiver
  scope :slack, -> { where(platform: 'Slack') }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :find_organization

  def show; end

  def edit; end

  def update
    if @organization.update(params.require(:organization).permit(:name, :emoji, :daily_budget))
      redirect_to organization_path
    else
      render :edit
    end
  end

  private

  def find_organization
    @organization = Organization.find_by(id: session[:organization_id])
    redirect_to root_path, alert: 'Unauthenticated' if @organization.blank?
  end
end

app/controllers/slack_controller.rb
# frozen_string_literal: true

class SlackController < ApplicationController
  skip_before_action :verify_authenticity_token
  wrap_parameters false

  def events
    @event = Event.slack.create!(data: request.request_parameters)

    if @event.data[:type] == 'url_verification'
      @event.completed!
      render json: { challenge: @event.data[:challenge] }
    else
      EventDispatchJob.perform_later(@event)
      head :ok
    end
  end

  def authorize
    connection = Faraday.new(
      url: 'https://slack.com',
      headers: { 'Content-Type' => 'application/x-www-form-urlencoded' }
    ) do |builder|
      builder.response :logger
      builder.request :authorization, :basic,
                      Rails.application.credentials.slack.client_id,
                      Rails.application.credentials.slack.client_secret
    end

    response = connection.post('/api/oauth.v2.access') do |req|
      req.params['code'] = params[:code]
    end

    auth_data = JSON.parse(response.body).with_indifferent_access

    return render(json: auth_data) unless auth_data[:ok]

    @organization = Authorization.slack.find_by(uid: auth_data.dig(:team, :id))&.organization
    if @organization.blank?
      ActiveRecord::Base.transaction do
        @organization = Organization.create!(name: auth_data.dig(:team, :name))
        @organization.authorizations.slack.create!(
          uid: auth_data.dig(:team, :id),
          access_token: auth_data[:access_token],
          refresh_token: auth_data[:refresh_token],
          expires_at: auth_data[:expires_in].seconds.from_now,
          data: auth_data
        )
      end
    end
    session[:organization_id] = @organization.id
    redirect_to organization_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<a href="https://slack.com/oauth/v2/authorize?client_id=2591696758993.3610713507764&scope=emoji:read,users:read,channels:join,channels:history,reactions:read&user_scope="><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcSet="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" /></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kudos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, message| %>
      <div role='alert'>
        <h2><%= message %></h2>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/organizations/edit.html.erb
<%= form_for @organization do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :emoji %>
    <%= f.text_field :emoji %>
  </div>
  <div>
    <%= f.label :daily_budget %>
    <%= f.number_field :daily_budget %>
  </div>
  <%= f.submit %>
<% end %>

app/views/organizations/show.html.erb
<h1><%= @organization.name %></h1>

<dl>
  <dt>Emoji</dt>
  <dd><%= @organization.emoji %></dd>
  <dt>Daily Budget</dt>
  <dd><%= @organization.daily_budget %></dd>
</dl>

<%= link_to "Edit", edit_organization_path %>